import esbuild from "esbuild";
import esbuildSvelte from "esbuild-svelte";
import process from "process";
import { builtinModules } from "node:module";
import { sveltePreprocess } from "svelte-preprocess";
import { nodeModulesPolyfillPlugin } from 'esbuild-plugins-node-modules-polyfill';
import { copyFileSync, existsSync } from "fs";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	plugins: [
		esbuildSvelte({
			compilerOptions: {css: "injected"},
			preprocess: sveltePreprocess()
		}),
		nodeModulesPolyfillPlugin(),
		{
			name: 'copy-styles',
			setup(build) {
				build.onEnd(() => {
					if (existsSync("styles.css")) {
						copyFileSync("styles.css", "dist/styles.css");
					}
				});
			},
		}
	],
	external: [
		"obsidian",
		"electron",
		"@electron/remote",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "dist/main.js",
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}